### ISSUE TITLE
Get new screenshots during local CD

### ISSUE THREAD

**Issue by nickmeinhold** [nickmeinhold/crowdleague_public#12]
[screenshots | Dart Package](https://pub.dev/packages/screenshots)
[An introduction to integration testing - Flutter](https://flutter.dev/docs/cookbook/testing/integration/introduction)

- [x] add screenshots.yaml 
- [x] add integration tests 
 
### Custom Scripts with Github Actions 
- [Take Screenshots With GitHub Actions](https://medium.com/better-programming/monitor-your-flutter-apps-health-end-to-end-with-github-actions-8a9fb1889c6a) 
- [How to Record Flutter Integration Tests With GitHub Actions](https://medium.com/better-programming/how-to-record-flutter-integration-tests-with-github-actions-1ca670eff94a)

**Comment by nickmeinhold** [comment]
had trouble running screenshots as described in 

[Cannot start the IOS simulator · Issue #169 · mmcc007/screenshots](https://github.com/mmcc007/screenshots/issues/169)

The fix described (get a particular version of screenshots) seems to have worked for me

**Comment by nickmeinhold** [comment]
I then had errors about the locale: 

```sh
executing: plutil -extract AppleLocale xml1 -o -
/Users/nick/Library/Developer/CoreSimulator/Devices/52446001-9355-47E9-B4EA-F0C791D4EE68/data/Library/Preferences/.GlobalPr
eferences.plist
[   +1 ms]
/Users/nick/Library/Developer/CoreSimulator/Devices/52446001-9355-47E9-B4EA-F0C791D4EE68/data/Library/Preferences/.GlobalPr
           eferences.plist: Could not extract value, error: No value at that key path or invalid key path: AppleLocale
           
Unhandled exception:
command failed: exitcode=1, cmd='plutil -extract AppleLocale xml1 -o - /Users/nick/Library/Developer/CoreSimulator/Devices/52446001-9355-47E9-B4EA-F0C791D4EE68/data/Library/Preferences/.GlobalPreferences.plist', workingDir=null
#0      cmd (package:screenshots/src/utils.dart:430:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:249:17)
```

I change the screenshots.yaml to use 

```yaml
locales:
 - en-AU
```

and also changed the language on the simulator to `english-au`, not sure what changed but it seems to work now.

**Comment by nickmeinhold** [comment]
The Android emulator produced an error with locale `en-AU` but setting back to:

```yaml
locales:
 - en-AU
```

seemed to fix that and works for iOS too.  

But now Android is throwing: 

```sh
Unhandled exception:
Error: emulator Android_Emulator not started: [{"event":"device.added","params":{"id":"emulator-5554","name":"emulator-5554","platform":"android-arm","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
```

**Comment by nickmeinhold** [comment]
Seems to be working now, with workaround described in #15
